### ISSUE TITLE
Error when creating a new project

### ISSUE THREAD

**Issue by Henryisthebest** [CKGrafico/Cordova-Multiplatform-Template#10]
I get a dialog box with the following

Title: Microsoft Visual Studio

Content: A problem was encountered creating the sub project 'Tasks'. The template specified cannot be found. Please check that the full path is correct.

**Comment by gbreeze** [comment]
You have to install the node.js tools.
https://github.com/CKGrafico/Cordova-Multiplatform-Template/tree/master/Tasks

**Comment by CKGrafico** [comment]
thanks @gbreeze
