### ISSUE TITLE
No se ve el botón de acción en el emulador Ripple

### ISSUE THREAD

**Issue by gabrielgt** [CKGrafico/Cordova-Multiplatform-Template#14]
No aparece en Ripple el botón de acción de la página Actions. En Windows 10 y Windows Phone sí aparece y funciona correctamente al pulsarlo.

![image](https://cloud.githubusercontent.com/assets/3408827/9857002/5fc613da-5b18-11e5-9aaa-83cc0fee7dcd.png)

**Comment by CKGrafico** [comment]
No puedo reproducir tu bug, he probado de crear con la última versión una app y tanto con android como con ios en ripple me va el icono.
Prueba con el emulador de android si puedes

**Comment by gabrielgt** [comment]
Con el emulador de Android sí me funciona:
![image](https://cloud.githubusercontent.com/assets/3408827/9861513/11c05914-5b33-11e5-8ab6-7b91049b589c.png)

**Comment by gabrielgt** [comment]
Por cierto con Ripple el botón no lo veo, pero está, y funciona al hacer click. Es solo un tema de presentación. ¿Es normal que no aparezcan tampoco los botones del móvil?

**Comment by gabrielgt** [comment]
Con iOS en Ripple también me aparece el botón.

**Comment by CKGrafico** [comment]
Parece algo de tu caché no deberías preocuparte.
En ripple no salen los botones del teléfono solo es un simulador.

**Comment by gabrielgt** [comment]
Creo que ya he encontrado el problema. En el fichero actions.html sobra la clase button-calm:

```javascript
<ion-view view-title="Actions">
    <ion-nav-buttons side="right">
        <button class="button button-clear BUTTON-CALM icon icon-only ion-ionic" ng-click="vm.exampleAction()"></button>
    </ion-nav-buttons>
...
```
Con ese cambio ya me funciona bien en todos los entornos. Pero me quedo con tres dudas:
1. ¿Por qué en el emulador de Android se veía bien?
2. ¿Por qué a ti se te ve bien en el simulador Ripple con Android?
3. ¿Qué branch está subida a la Visual Studio Gallery?
