### ISSUE TITLE
How do i run it? (Non Vistual Studio User)

### ISSUE THREAD

**Issue by bferreirainfo** [CKGrafico/Cordova-Multiplatform-Template#15]
when I run "ionic serve," the screen goes blank saying that has multiple missing files.

**Comment by CKGrafico** [comment]
try this
```
> npm install
> gulp initialize
> ionic serve
```

**Comment by bferreirainfo** [comment]
Hi CK, thanks for respond.

I got the same This is what i did
cd ...\Cordova-Multiplatform-Template-master\App
npm install ( installed everything)
gulp initialize (installed everything)
ionic serve (same error)
Chrome log:
http://localhost:8100/css/main.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/css/platform.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/js/platformOverrides.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/scripts/appbundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/css/main.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/css/platform.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by CKGrafico** [comment]
Ok your workflow is different because you're not using Visual Studio (that automatize tasks)
To compile sass files and inject use
```
> gulp
```
But first you need to compile TS files, I didn't make a task for this I will upload ASAP
thanks!

**Comment by bferreirainfo** [comment]
I am just a ionic cli guy hahaha with no TS or SASS skills =(... but thanks for the help.

**Comment by CKGrafico** [comment]
check https://github.com/CKGrafico/Cordova-Multiplatform-Template/commit/fddadab7a3f8fe1aca16478f22234740a81c8cd2

// Working without Visual Studio
    // 1.- npm install
    // 2.- gulp initialize
    // 3.- gulp watch

// Working with Visual Studio
    // 1.- npm install
    // 2.- gulp initialize
