### ISSUE TITLE
Add ng-cordova

### ISSUE THREAD

**Issue by CKGrafico** [CKGrafico/Cordova-Multiplatform-Template#18]
Add ng-cordova

**Comment by CKGrafico** [comment]
Discarted

**Comment by Jonatthu** [comment]
How can I add ngCordova here?

**Comment by CKGrafico** [comment]
You can add to your bower file
http://ngcordova.com/docs/install/

**Comment by Jonatthu** [comment]
Cordova.js is not in my www folder :C

**Comment by CKGrafico** [comment]
using VS template? or zip? if is a zip you have to init cordova app :) https://cordova.apache.org/#getstarted
