### ISSUE TITLE
Problem with default:scss / lazy-result.js

### ISSUE THREAD

**Issue by cjmackenzie40** [CKGrafico/Cordova-Multiplatform-Template#20]
I added the template to a new Visual Studio project, waited for auto npm installation. Then I opened the Task Runner Explorer - gulp: initialise ran.
Now when I run a Build I get an error in the Task Runner Explorer:

> Starting 'default:scss'...
C:\...\lazy-result.js:152
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined

I also have the Ionic CLI installed, so in command window, I tried `gulp`
I got a different error :

>The `libsass` binding was not found in C:\...\node_modules\node-sass\vendor\win32-x64-46\binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

So I did that, then `ionic serve` - and the app appears to run. 

Back to Visual Studio - same error (Promise is not defined). Tried cleaning and re-building, no success

**Comment by CKGrafico** [comment]
Hi, the problem if that you have different node version in VS.
This fix the problem http://blogs.msdn.com/b/webdev/archive/2015/03/19/customize-external-web-tools-in-visual-studio-2015.aspx 

I will add to FAQ.

**Comment by cjmackenzie40** [comment]
That's it, problem solved
