### ISSUE TITLE
Build failed in visual studio 2015 for windows platform

### ISSUE THREAD

**Issue by wasimbeniwale** [CKGrafico/Cordova-Multiplatform-Template#23]
I have following configuration:
- Visual Studio 2015 (Community Edition) with Cordova tools checked during installation of VS.
- Node.js installed:  version 5.1
- Node.js tools 1.1 for Visual Studio 2015
- npm version: 3.4.0
- bower version: 1.6.5
- Cordova version: 5.4.0
- Ionic version: 1.7.10

And I have also tried to clear cordova cache from cordova tools but have no success.

<b>Error:</b> The edge module has not been pre-compiled for node.js version v5.1.0. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.

also got error of <b>npm install failed</b> with exit code 1 during build process.

And after running the <b>dependency checker</b> got issue with the Joyent Node.js missing rather I have a latest version of node.js

**Comment by CKGrafico** [comment]
Mmm first time I see that, please check this https://github.com/CKGrafico/Cordova-Multiplatform-Template/wiki/Frequently-Asked-Questions-(FAQ) (FAQ 3)

**Comment by nathansmetelak** [comment]
I've got the same issue.  First time using Cordova, so it could be ignorance.

**Comment by ronakvala** [comment]
I've got the same issue. First time using Cordova in VS2015.

**Comment by patrickCode** [comment]
Got the same issue. I have tried installing vs-tav manually but getting the error - The edge module has not been pre-compiled for node.js version v5.3.0. You must build a custom version of edge.node

**Comment by nathansmetelak** [comment]
@patrickCode You're right.  I ended up going the other route and installing an older version of node.  Did you go through the process to build a new edge.node?  If so, what were the steps?

**Comment by ronakvala** [comment]
@patrickCode @wasimbeniwale I found workaround to this. First you need to run the dependency checker to verify that all required components are installed and configured properly.

Here is how you can do it: Go to VS2015 > Tools > Options > Tools for Apache Cordova > Play Run Dependency Checker button
![capture2](https://cloud.githubusercontent.com/assets/16712496/12382732/2fafacd6-be02-11e5-9288-b68d82ec93a5.PNG)


In my case, it was failing for Joyent Node.js even though I had Node.js installed from a long before I installed VS2015 and I also checked Joyent Node.js when I was installing the VS2015.

After trying multiple things I decided to uninstall Git and Node.js from my machine, and then I went to Control Panel where I chose VS2015 Change option so I can modify components. After I uninstall Git and Node.js it allowed me to re-install Joyent Node.js and Git components so I checked them and installed those two components.

![capture2](https://cloud.githubusercontent.com/assets/16712496/12382826/4934a188-be03-11e5-9f97-8790ff421f5b.PNG)

I restarted my machine and VS2015 and again I ran dependency checker and the error was gone and I was able to build my project successfully.

Let me know if you have any questions.

Hope this helps.

**Comment by CKGrafico** [comment]
kudos @ronakvala :)
