### ISSUE TITLE
JS code not updating on the fly

### ISSUE THREAD

**Issue by kharatps02** [CKGrafico/Cordova-Multiplatform-Template#29]
Javascript code is not updating on the fly when made changes into TS code 
 >> step to reproduce 
 - run gulp watch commands on cmd
 - modified ts files 
 - observe app.js 
It's not updating on the fly .

**Comment by CKGrafico** [comment]
Interesting bug, thanks I will check ASAP

**Comment by CKGrafico** [comment]
ASAP is not today I'm sorry

**Comment by CKGrafico** [comment]
Will solve on the new version
