### ISSUE TITLE
Continuous Integration with VS on a MAC

### ISSUE THREAD

**Issue by jrmcdona** [CKGrafico/Cordova-Multiplatform-Template#39]
Hi, 
I downloaded Visual studio on a MAC.   I am curious if your plugin can help me achieve continous integration such as we see in this blog!

https://blogs.msdn.microsoft.com/mvpawardprogram/2015/10/27/continuous-integration-with-ionic-framework-using-visual-studio-online-from-check-in-to-device/

Thanks!

**Comment by CKGrafico** [comment]
this is a template not a plugin, VS for mac is not currently supporting cordova :(
