### ISSUE TITLE
Cordova run --> into Android device -- > white blank page

### ISSUE THREAD

**Issue by sureshpathi10** [CKGrafico/Cordova-Multiplatform-Template#44]
I've downloaded and tried to run with "Cordova run" command.
but I get only blank white screen. could anyone help to find the issue?

note: I've installed node.js, cordova & ionic.

**Comment by CKGrafico** [comment]
Are you installing the dependencies? #40

**Comment by sureshpathi10** [comment]
Yes. I installed Node.js, Cordova & Ionic. is there anything else required ?

**Comment by Trumind** [comment]
There is no debug directory that is specified in the index file under www directory

if you can check the index file file you will see stuff like this but they dont exist
`debug/main.css`
`platform.css`
`cordova.js`

This App is `incomplete!

**Comment by CKGrafico** [comment]
Did you run the tasks?
