### ISSUE TITLE
error TS2304 and TS2303: cannot find name 'angular' and namespaces 'ng' and 'ionic'

### ISSUE THREAD

**Issue by Loulou54** [CKGrafico/Cordova-Multiplatform-Template#45]
Hi,
I follow the command line installation process on Windows10 (in powershell) and at the step "gulp watch" or "gulp", I have the error in the title for all occurrences of angular, ng or ionic in the app.ts file and in the modules files.
I can't solve this issue, thank you for your help.

**Comment by CKGrafico** [comment]
check #40

**Comment by Engwi** [comment]
Good Day,
This particular issue is driving me insane. 

What exactly, in the instructions, did I miss ? Followed them from top to bottom, installed dependencies, when getting to run "gulp" - A multitude of these errors are presented :

error TS2503: Cannot find namespace 'ionic'.
error TS2304: Cannot find name 'angular'.
error TS2503: Cannot find namespace 'ng'.
  
Please Mr. Author, point out what I am missing here :-) !

**Comment by Engwi** [comment]
Sigh... the instructions referred : gulp initialize _download bower and tsd dependencies_ 
made me think tsd dependencies will be installed - not the case.. had to run "tsd install" separately.

All good - working now ! :-)

**Comment by Kaoschuks** [comment]
Pls can you share the code you ran because am having the same error here (using linux os)
error TS2503: Cannot find namespace 'ionic'.
error TS2304: Cannot find name 'angular'.
error TS2503: Cannot find namespace 'ng'.

**Comment by holodny** [comment]
npm install -g tsd
