### ISSUE TITLE
How to install and run template in ionic 1 cli

### ISSUE THREAD

**Issue by Kaoschuks** [CKGrafico/Cordova-Multiplatform-Template#47]
I have downloaded the template how do I install it and run using ionic serve in ionic1

**Comment by CKGrafico** [comment]
#40

**Comment by Kaoschuks** [comment]
Having error cannot fin namespace angular, namespace ionic ng etc when running gulp

Please can I have a list of working commands

**Comment by CKGrafico** [comment]
Please read the docs https://github.com/CKGrafico/Cordova-Multiplatform-Template#first-steps-1
