### ISSUE TITLE
Getting Project to Run

### ISSUE THREAD

**Issue by holodny** [CKGrafico/Cordova-Multiplatform-Template#48]
¡Saludos desde La Florida y gracias por compartir tu proyecto!  I'm new to Apache Cordova (not so much to node/npm though) and your project was the first project that I tried out.  Like some others, I had issues with namespaces and the missing plugin and to get things to run, I did this in the APP (root) directory of the project:

cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-console

npm install -g tsd

After this, I no longer get any missing name/namespace warnings and my cordova_plugins.js file is present.

**Comment by CKGrafico** [comment]
thanks for your comments

**Comment by CKGrafico** [comment]
Thanks for your comments!
