### ISSUE TITLE
How do I build the vsix?

### ISSUE THREAD

**Issue by arlair** [CKGrafico/Cordova-Multiplatform-Template#7]
Hi, I was playing with this and trying to create the latest build of the template locally. I have tried Visual Studio 2015 RC and Visual Studio 2012 and download Visual Studio RC 2015 SDK and Visual Studio 2012 SDK.

I load Visual Studio Template.sln, but it tells me the project is unsupported. Any ideas on what I need installed? Thanks.

**Comment by CKGrafico** [comment]
Hi, this github repo is for development. 
Please download and use the Visual Studio template https://visualstudiogallery.msdn.microsoft.com/407fc1f8-538b-4beb-b2b2-69afcb6fbd96 (only for >= Visual Studio 2015 RC)

**Comment by arlair** [comment]
Yes, I found that before, but I wanted to modify it and build my own version of the template.

**Comment by CKGrafico** [comment]
With Visual Studio 2012 you won't be able to open the project.
With Visual Studio 2015 RC, did you try this?

![Open Project template](http://i.imgur.com/rfZL0Rn.gif)

Is very very very important to have the exact version of VS to open the project or you can make your vsix on Visual Studio > New project > Visual Studio template

**Comment by arlair** [comment]
I double checked and I had downloaded Visual Studio 2015 RC SDK, but it was not installed. I have it loading and compiling now. Thanks again and sorry for the confusion.
