### ISSUE TITLE
Missing main.css

### ISSUE THREAD

**Issue by ashleydb** [CKGrafico/Cordova-Multiplatform-Template#8]
I'm using Win10 tech preview with VS Community 2015 RC and Node.js Tools 1.1 Beta. Installed this template from VS gallery, updated it tonight with the latest version.

Thanks for fixing the readme.

I had to run initialize twice. First run errors on a lock file. Not big deal, so I didn't look at fixing it.

When trying to run the app though, using the defaults of Android in Ripple, it crashes.

It seems to be because of a missing main.css, which tells me something is going wrong with default.scss.

If I run that command I see the problem is a missing file, so the following needs to be commented main.scss, (or you need to add a custom file):
    `//@import "themes/custom";`

FWIW, I also changed up the gulpfile.js to look like this:
    `// Tasks`
    `gulp.task('initialize', ['initialize:bower', 'default']);`
    `gulp.task('default', ['default:scss', 'default:inject']);`

Thanks for the template.
Ash

**Comment by CKGrafico** [comment]
Thanks Ash, I will double check this soon

**Comment by CKGrafico** [comment]
If you want you can try with v0.5.3.2 and Task Documentation

**Comment by CKGrafico** [comment]
Checked and works fine :D
